#ifndef COMMON_H
#define COMMON_H

/*
 * include autogenerated config header
 */

#include "config.h"

/* 
 * windows check 
 */ 
 
#if !defined(_windows_) && (defined(WIN32) || defined(_WIN32) || defined(__WIN32) || defined(__WIN32__))
#       define _windows_ 1 
#endif 

/*
 * library exportation definition
 */

#ifdef _windows_
#       define _export __declspec(dllexport)
#else
#       define _export __attribute__((visibility("default")))
#endif

/*
 * common headers
 */

#include <math.h>
#include <stdint.h>

#endif
